DEBUG ``` Running experiment with standard cross-attention Number of Transformer parameters: 325248 Tracking run with wandb version 0.17.5 Run data is saved locally in /content/wandb/run-20240804_025520-uwc04slf Syncing run 0804_0254_cross_attention_ablation_study_standard to Weights & Biases (docs) View project at https://wandb.ai/cursivetransformer/cursivetransformer View run at https://wandb.ai/cursivetransformer/cursivetransformer/runs/uwc04slf --------------------------------------------------------------------------- TypeError                                 Traceback (most recent call last) <ipython-input-35-753a822ede75> in <cell line: 79>()      79 for attention_type in args.cross_attention_types:      80     print(f"\nRunning experiment with {attention_type} cross-attention") ---> 81     model, best_loss = run_experiment(attention_type)      82     results[attention_type] = {      83         'best_test_loss': best_loss,
8 frames
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py in _call_impl(self, *args, **kwargs)
   1539                 or _global_backward_pre_hooks or _global_backward_hooks
   1540                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1541             return forward_call(*args, **kwargs)
   1542 
   1543         try:

TypeError: CrossAttention.forward() missing 1 required positional argument: 'context'
```